import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { ThemeProvider } from '@/components/Theme-provider'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await auth()

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <ThemeProvider attribute="class" forcedTheme="dark" storageKey="">
          <body className={inter.className}>
            <Navbar/>
            {children}</body>
        </ThemeProvider>
      </html>
    </SessionProvider>
  )
}
